# Generated by Django 4.2.21 on 2025-06-02 14:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('failed', 'Отклонена')], default='completed', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_bets',
            field=models.IntegerField(default=0, verbose_name='Всего ставок'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_winnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Общая сумма выигрышей'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='won_bets',
            field=models.IntegerField(default=0, verbose_name='Выиграно ставок'),
        ),
    ]
