# Generated by Django 4.2.21 on 2025-06-02 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_transaction_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('failed', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
